### ISSUE TITLE
Pi Node打不开，最后一步一直在转圈

### ISSUE THREAD

**Issue by 17301090502** [muratyurdakul75/picheck#1]
Pi Node打不开，最后一步一直在转圈，节点不能正常运行，请给与技术支持，谢谢！！！

**Comment by muratyurdakul75** [comment]
你好。通过电子邮件将您的 TELEGRAM 地址发送给我。让我从那里联系您并帮助您。只需在您的计算机上安装 UltraView
应用程序即可。我可以远程连接并帮助您。


3 Eki 2023 Sal, saat 18:07 tarihinde 17301090502 ***@***.***>
şunu yazdı:

**Comment by 17301090502** [comment]
辛苦您，直接远程吧，谢谢！
您哪里用那个远程方便呢？

**Comment by muratyurdakul75** [comment]
我使用 UltraView 应用程序进行远程连接和协助。

我之前用的是TeamViewer。但由于我使用它太多，它现在要求我提供许可证。😂

这就是我现在可以使用 UltraView 的原因。




3 Eki 2023 Sal, saat 18:25 tarihinde 17301090502 ***@***.***>
şunu yazdı:

**Comment by 17301090502** [comment]
请您告诉我去哪找 TELEGRAM 地址，我不是很明白

**Comment by 17301090502** [comment]
我只有“向日葵”或电脑远程连接

**Comment by muratyurdakul75** [comment]
https://www.ultraviewer.net

 

您可以从此链接下载它。 然后您可以发送电子邮件至 "myurdakul@hotmail.com"

**Comment by 17301090502** [comment]
72121048是这个吗



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月03日 23:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

https://www.ultraviewer.net



您可以从此链接下载它。 然后您可以发送电子邮件至 ***@***.***

**Comment by 17301090502** [comment]
72121048是这个吗密码是97546



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月03日 23:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

https://www.ultraviewer.net



您可以从此链接下载它。 然后您可以发送电子邮件至 ***@***.***

**Comment by 17301090502** [comment]
我的邮箱m17301090502@163.com

**Comment by 17301090502** [comment]
回复您的邮件了

**Comment by 17301090502** [comment]
只作节点



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月03日 23:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

https://www.ultraviewer.net



您可以从此链接下载它。 然后您可以发送电子邮件至 ***@***.***

**Comment by 17301090502** [comment]
别的都不用



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月03日 23:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

https://www.ultraviewer.net



您可以从此链接下载它。 然后您可以发送电子邮件至 ***@***.***

**Comment by 17301090502** [comment]
您亲苦给整理一下，我不会弄



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月03日 23:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

https://www.ultraviewer.net



您可以从此链接下载它。 然后您可以发送电子邮件至 ***@***.***

**Comment by 17301090502** [comment]
非常感谢您的支持和帮助，我自己弄了很长时间了，一直弄不好，再次感谢您和平台的打了支持，信心满满，中国区先锋为你们点赞！！！！！！！！！！
       欢迎您到中国来，北京欢迎您！

**Comment by muratyurdakul75** [comment]
☺️🥰

3 Eki 2023 Sal, saat 20:42 tarihinde 17301090502 ***@***.***>
şunu yazdı:

**Comment by 17301090502** [comment]
您好！端口打不开，您辛苦给弄一下吧。谢谢！！！

**Comment by muratyurdakul75** [comment]
您需要从调制解调器接口进行端口转发。我今天没空。你试试端口转发。如果没有，我明天将远程连接并提供帮助。


4 Eki 2023 Çar, saat 03:26 tarihinde 17301090502 ***@***.***>
şunu yazdı:

**Comment by 17301090502** [comment]
好的，早晨弄了，没弄好，你明天有空时给我弄一下吧！辛苦您了，谢谢！

**Comment by 17301090502** [comment]
共享容器找不到了，早上同步了，现在又不同步了！

**Comment by 17301090502** [comment]
我不敢动了，越弄越不好！

**Comment by muratyurdakul75** [comment]
https://t.me/picheck_chat

Telegram ☺️

4 Eki 2023 Çar, saat 08:35 tarihinde 17301090502 ***@***.***>
şunu yazdı:

**Comment by 17301090502** [comment]
您好！722121048/97546



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月04日 14:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

https://t.me/picheck_chat

Telegram ☺️

4 Eki 2023 Çar, saat 08:35 tarihinde 17301090502 ***@***.***>
şunu yazdı:

**Comment by 17301090502** [comment]
您好！ 72121048/97546

**Comment by muratyurdakul75** [comment]
我没空。明天我可以支持你。


4 Eki 2023 Çar, saat 11:16 tarihinde 17301090502 ***@***.***>
şunu yazdı:

**Comment by 17301090502** [comment]
***@***.***



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月04日 14:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

https://t.me/picheck_chat

Telegram ☺️

4 Eki 2023 Çar, saat 08:35 tarihinde 17301090502 ***@***.***>
şunu yazdı:

**Comment by 17301090502** [comment]
您好！在吗？ID72121048/97546

**Comment by 17301090502** [comment]
好，大概几点



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月04日 16:29 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

我没空。明天我可以支持你。


4 Eki 2023 Çar, saat 11:16 tarihinde 17301090502 ***@***.***>
şunu yazdı:

**Comment by muratyurdakul75** [comment]
明天。 20:00 土耳其时间


4 Eki 2023 Çar, saat 11:53 tarihinde 17301090502 ***@***.***>
şunu yazdı:

**Comment by 17301090502** [comment]
好的👌谢谢！



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月04日 18:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

明天。 20:00 土耳其时间


4 Eki 2023 Çar, saat 11:53 tarihinde 17301090502 ***@***.***>
şunu yazdı:

**Comment by 17301090502** [comment]
您好



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月04日 18:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

明天。 20:00 土耳其时间


4 Eki 2023 Çar, saat 11:53 tarihinde 17301090502 ***@***.***>
şunu yazdı:

**Comment by muratyurdakul75** [comment]
您好

 

UltraView ID Password? 😊

**Comment by 17301090502** [comment]
今天忙吗，有时间吗！？



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月04日 18:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

明天。 20:00 土耳其时间


4 Eki 2023 Çar, saat 11:53 tarihinde 17301090502 ***@***.***>
şunu yazdı:

**Comment by muratyurdakul75** [comment]
我现在有空。

**Comment by 17301090502** [comment]
您好！ 72121048/97546

**Comment by 17301090502** [comment]
现在可以吗

**Comment by muratyurdakul75** [comment]
我不明白 不需要远程连接吗？

**Comment by 17301090502** [comment]
需要

**Comment by muratyurdakul75** [comment]
72121048/97546

 

我无法连接到这些信息。 UltraView 应用程序是否已关闭？

**Comment by 17301090502** [comment]
1D72121048/84468



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月06日 00:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

我不明白 不需要远程连接吗？

**Comment by 17301090502** [comment]
可以



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月06日 00:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

72121048/97546



我无法连接到这些信息。 UltraView 应用程序是否已关闭？

**Comment by muratyurdakul75** [comment]
您可以从列表中选择英语吗？ 

或者如果调制解调器设置中有英语选项会更好。

**Comment by 17301090502** [comment]
请教您一下，能不能不用加速器起动节点，有人说用加速器节点端囗就打开，只能输出，不能传入数据



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月06日 01:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

您可以从列表中选择英语吗？

或者如果调制解调器设置中有英语选项会更好。

**Comment by muratyurdakul75** [comment]
您的互联网 IP 地址不断变化。 我认为中国的口岸开放方式有所不同。 或者也许您需要购买固定IP。 不知道国内能不能有固定IP。 需要咨询国内其他PiNode运行人员。 我从调制解调器接口进行端口转发，没有问题。 但不幸的是我无能为力打开端口。

**Comment by 17301090502** [comment]
可以更改一下以太网的IP挷定



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月06日 01:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

您的互联网 IP 地址不断变化。 我认为中国的口岸开放方式有所不同。 或者也许您需要购买固定IP。 不知道国内能不能有固定IP。 需要咨询国内其他PiNode运行人员。 我从调制解调器接口进行端口转发，没有问题。 但不幸的是我无能为力打开端口。

**Comment by 17301090502** [comment]
国内都是这样弄的



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月06日 01:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

您的互联网 IP 地址不断变化。 我认为中国的口岸开放方式有所不同。 或者也许您需要购买固定IP。 不知道国内能不能有固定IP。 需要咨询国内其他PiNode运行人员。 我从调制解调器接口进行端口转发，没有问题。 但不幸的是我无能为力打开端口。

**Comment by 17301090502** [comment]
我先弄一下，您在给试一下吧



---- 回复的原邮件 ----
| 发件人 | Murat ***@***.***> |
| 日期 | 2023年10月06日 01:34 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [muratyurdakul75/picheck] Pi Node打不开，最后一步一直在转圈 (Issue #1) |

您的互联网 IP 地址不断变化。 我认为中国的口岸开放方式有所不同。 或者也许您需要购买固定IP。 不知道国内能不能有固定IP。 需要咨询国内其他PiNode运行人员。 我从调制解调器接口进行端口转发，没有问题。 但不幸的是我无能为力打开端口。

**Comment by muratyurdakul75** [comment]
我已经修复了以太网 IP 地址。 我将其固定为 192.168.0.18。 你的问题是不同的。 您的 WAN IP（互联网 IP）不断变化。 不是固定IP。 因此，无法进行端口转发。 你需要问问你所在国家的其他朋友。 也许你应该使用VPN。
