### ISSUE TITLE
Monitoring: Latest block, wrong unit of measure?

### ISSUE THREAD

**Issue by olieske** [muratyurdakul75/picheck#5]
When I compare "Latest Block" in picheck 13.0.0 and Node Software 0.4.9 I see a discrepancy when node is syncing.

Node Software: "Latest Block: 27 minutes ago."
PiCheck: "Latest Block: 27 hours ago"
<img width="1537" alt="Bildschirmfoto 2024-04-05 um 09 56 40" src="https://github.com/muratyurdakul75/picheck/assets/19210011/fc825050-9056-446d-94b8-c107f41c52f2">

**Comment by muratyurdakul75** [comment]
I made a small text error. I will release the new version soon.
